### ISSUE TITLE
What do Asians use sulfur for?

### ISSUE THREAD

**Issue by HiranChaudhuri** [paulwedeck/settlers-remake#52] opened 2022-06-06 06:20 UTC
It seems Asians can create sulfur mines, but I do not see where that resource would actually get used.
Wasn't it that they could create fireworks or cannons?

**Comment by paulwedeck** [comment] 2022-06-06 10:44
Yes, but this is not yet implemented.
I will close this because it's a duplicate of #13

**Closed by paulwedeck** 2022-06-06 10:44 UTC
